export enum ApplicationStatus {
   IN_GAME = "IN_GAME",
   VOTING = "VOTING",
   VOTED = "VOTED",
   GAME_ROUND_STARTED = "GAME_ROUND_STARTED",
   IN_LOBBY = "IN_LOBBY",
   LOADING = "LOADING",
   GAME_ABORTED_LACK_OF_PLAYERS = "GAME_ABORTED_LACK_OF_PLAYERS",
   GAME_ABORTED_HOST_LEFT = "GAME_ABORTED_HOST_LEFT",
   GAME_FINISHED = "GAME_FINISHED",
}
