export enum ApplicationPage {
   LOGIN_PAGE = "LOGIN_PAGE",
   CREATE_LOBBY_PAGE = "CREATE_LOBBY_PAGE",
   MAIN_PAGE = "MAIN_PAGE",
   LOBBY_LIST_PAGE = "LOBBY_LIST_PAGE",
   LOBBY_PAGE = "LOBBY_PAGE",
   GAME_PAGE = "GAME_PAGE",
   HOST_DISCONNECTED_PAGE = "HOST_DISCONNECTED_PAGE",
   GAME_ENDED_PAGE = "GAME_ENDED_PAGE",
}
