export enum JoinStatus {
   SUCCESS = "SUCCESS",
   LOBBY_FULL = "LOBBY_FULL",
   LOBBY_NOT_FOUND = "LOBBY_NOT_FOUND",
   USER_ALREADY_IN_LOBBY = "USER_ALREADY_IN_LOBBY",
   USER_HOST_GAME = "USER_HOST_GAME",
}
